In [2]:
import torch
import torch.nn as nn

In [6]:
a = torch.randn(2,3)
a

tensor([[-1.2069, -2.0828, -0.0073],
        [ 1.3928, -0.2102, -0.7780]])

In [9]:
a.sum(dim=1, keepdim=True)

tensor([[-3.2970],
        [ 0.4046]])

In [ ]:
from tqdm import tqdm
from time import sleep
for i in tqdm(range(10000)):
     sleep(0.01)

In [ ]:
import pandas as pd

pd.read_csv()

In [26]:
a = torch.as_tensor([1,2,3,4])
b = torch.as_tensor([[1,0,2], [1,0,2], [1,0,2], [1,0,2]])

In [78]:
import numpy as np
condition = (b - a[:, None] < 1)
valid_triplets = torch.where(condition == 1)
valid_triplets

(tensor([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 tensor([0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [79]:
(a[:, None] - b + b)[valid_triplets]

tensor([1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [71]:
a[:,None].repeat_interleave(3,1)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])

In [67]:
(a[:, None] - b + b)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])

In [69]:
a[:,None]

tensor([[1],
        [2],
        [3],
        [4]])

In [74]:
indexes = (a[:, None] - b + b)[valid_triplets]

In [80]:
a[valid_triplets[0]]

tensor([1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [85]:
torch.dist(a.double(),torch.as_tensor([2,3,4,5]).double())

tensor(2., dtype=torch.float64)

In [89]:
n = torch.nn.functional.normalize(torch.as_tensor([[1,2,3,4]]).double())

In [91]:
torch.dist(n[0], torch.as_tensor([0,0,0,0]).double())

tensor(1.0000, dtype=torch.float64)

In [ ]:
torch.as_tensor